In [1]:
import numpy as np 
import pandas as ps 
import matplotlib.pyplot as plt 
import tensorflow as tf



2024-03-12 16:08:29.957359: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-03-12 16:08:30.009122: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-03-12 16:08:30.009161: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-03-12 16:08:30.010346: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-03-12 16:08:30.019189: I tensorflow/core/platform/cpu_feature_guar

In [2]:
tf.__version__

'2.15.0'

In [3]:
dataset= ps.read_csv("Iris.csv")
x = dataset.iloc[:, 1:5].values
y = dataset.iloc[:, -1].values 

In [4]:
dataset.head()

Id    SepalLengthCm   SepalWidthCm   PetalLengthCm   PetalWidthCm   \
0     1             5.1            3.5             1.4            0.2   
1     2             4.9            3.0             1.4            0.2   
2     3             4.7            3.2             1.3            0.2   
3     4             4.6            3.1             1.5            0.2   
4     5             5.0            3.6             1.4            0.2   

       Species  
0  Iris-setosa  
1  Iris-setosa  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [5]:
dataset.corr

<bound method DataFrame.corr of      Id    SepalLengthCm   SepalWidthCm   PetalLengthCm   PetalWidthCm   \
0       1             5.1            3.5             1.4            0.2   
1       2             4.9            3.0             1.4            0.2   
2       3             4.7            3.2             1.3            0.2   
3       4             4.6            3.1             1.5            0.2   
4       5             5.0            3.6             1.4            0.2   
..    ...             ...            ...             ...            ...   
145   146             6.7            3.0             5.2            2.3   
146   147             6.3            2.5             5.0            1.9   
147   148             6.5            3.0             5.2            2.0   
148   149             6.2            3.4             5.4            2.3   
149   150             5.9            3.0             5.1            1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2

In [6]:

from tensorflow.keras.layers import Dense 
model = tf.keras.models.Sequential()


2024-03-12 16:08:32.174523: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-12 16:08:32.227607: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-12 16:08:32.227677: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-12 16:08:32.234840: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:887] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-03-12 16:08:32.234951: I external/local_xla/xla/stream_executor

In [7]:
model.add(tf.keras.layers.Dense(units=4, activation="relu"))
model.add(tf.keras.layers.Dense(units=10, activation="relu"))
model.add(tf.keras.layers.Dense(units=3, activation="softmax"))

model.compile(optimizer= 'adam', loss="sparse_categorical_crossentropy", metrics=['accuracy'])


In [8]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [9]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y = lb.fit_transform(y)

In [10]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [11]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=23)

In [13]:
print(y_train)

[0 1 0 2 0 0 1 1 1 2 2 0 1 0 1 2 2 2 0 1 2 2 0 2 1 1 2 1 0 2 1 0 1 0 2 1 1
 2 2 1 0 0 2 0 0 2 2 1 0 1 2 1 2 2 1 0 1 2 2 1 0 1 1 1 2 1 1 2 2 2 0 2 1 0
 2 2 0 1 1 2 0 0 1 0 1 1 0 2 1 1 0 2 1 2 2 1 0 0 2 2 1 0 2 1 2 1 0 0 0 2 0
 0 2 0 1 0 1 0 0 1]


In [14]:
print(x_train)

[[4.9 3.1 1.5 0.1]
 [5.2 2.7 3.9 1.4]
 [5.4 3.9 1.3 0.4]
 [7.7 2.8 6.7 2. ]
 [5.  3.4 1.5 0.2]
 [5.4 3.9 1.7 0.4]
 [6.5 2.8 4.6 1.5]
 [5.  2.3 3.3 1. ]
 [5.7 3.  4.2 1.2]
 [6.3 3.3 6.  2.5]
 [6.9 3.2 5.7 2.3]
 [4.8 3.4 1.9 0.2]
 [5.5 2.4 3.7 1. ]
 [4.6 3.2 1.4 0.2]
 [6.3 2.3 4.4 1.3]
 [6.3 2.5 5.  1.9]
 [4.9 2.5 4.5 1.7]
 [7.9 3.8 6.4 2. ]
 [4.9 3.1 1.5 0.1]
 [5.7 2.8 4.1 1.3]
 [7.4 2.8 6.1 1.9]
 [6.2 3.4 5.4 2.3]
 [5.5 4.2 1.4 0.2]
 [6.1 2.6 5.6 1.4]
 [5.4 3.  4.5 1.5]
 [7.  3.2 4.7 1.4]
 [7.7 3.8 6.7 2.2]
 [5.9 3.  4.2 1.5]
 [5.  3.6 1.4 0.2]
 [6.5 3.2 5.1 2. ]
 [6.7 3.  5.  1.7]
 [4.7 3.2 1.6 0.2]
 [5.8 2.6 4.  1.2]
 [5.1 3.3 1.7 0.5]
 [6.4 2.8 5.6 2.1]
 [5.5 2.3 4.  1.3]
 [6.8 2.8 4.8 1.4]
 [6.4 2.8 5.6 2.2]
 [5.8 2.8 5.1 2.4]
 [6.3 2.5 4.9 1.5]
 [4.9 3.1 1.5 0.1]
 [5.  3.4 1.6 0.4]
 [6.3 3.4 5.6 2.4]
 [4.9 3.  1.4 0.2]
 [4.8 3.4 1.6 0.2]
 [6.8 3.  5.5 2.1]
 [5.8 2.7 5.1 1.9]
 [5.5 2.5 4.  1.3]
 [4.4 2.9 1.4 0.2]
 [5.6 3.  4.1 1.3]
 [6.4 2.7 5.3 1.9]
 [6.2 2.2 4.5 1.5]
 [6.5 3.  5.

In [15]:
print(x_test)

[[6.9 3.1 5.4 2.1]
 [7.2 3.2 6.  1.8]
 [5.8 2.7 4.1 1. ]
 [4.6 3.1 1.5 0.2]
 [5.7 2.5 5.  2. ]
 [6.9 3.1 4.9 1.5]
 [5.7 3.8 1.7 0.3]
 [6.4 3.1 5.5 1.8]
 [5.4 3.4 1.7 0.2]
 [5.6 2.9 3.6 1.3]
 [6.1 2.8 4.7 1.2]
 [4.8 3.1 1.6 0.2]
 [7.1 3.  5.9 2.1]
 [5.1 3.8 1.5 0.3]
 [5.4 3.7 1.5 0.2]
 [6.3 2.8 5.1 1.5]
 [6.4 3.2 4.5 1.5]
 [6.1 2.9 4.7 1.4]
 [7.7 3.  6.1 2.3]
 [5.2 3.4 1.4 0.2]
 [6.4 3.2 5.3 2.3]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.7 3.2 1.3 0.2]
 [6.7 3.1 5.6 2.4]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.9 0.4]
 [6.2 2.8 4.8 1.8]
 [6.6 3.  4.4 1.4]
 [5.6 2.5 3.9 1.1]]


In [16]:
print(y_test)

[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 2 1 1 2 0 2 0 0 0 2 0 0 2 1 1]


In [17]:
model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test))

Epoch 1/50


2024-03-12 16:08:34.262448: I external/local_tsl/tsl/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2024-03-12 16:08:34.377422: I external/local_xla/xla/service/service.cc:168] XLA service 0x7f9600024000 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-03-12 16:08:34.377489: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Ti Laptop GPU, Compute Capability 8.6
2024-03-12 16:08:34.388160: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-03-12 16:08:34.412472: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8904
I0000 00:00:1710239914.540985   12060 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


4/4 [==============================] - 2s 89ms/step - loss: 3.4724 - accuracy: 0.3500 - val_loss: 3.7516 - val_accuracy: 0.2667
Epoch 2/50
4/4 [==============================] - 0s 21ms/step - loss: 3.3065 - accuracy: 0.3500 - val_loss: 3.5748 - val_accuracy: 0.2667
Epoch 3/50
4/4 [==============================] - 0s 20ms/step - loss: 3.1588 - accuracy: 0.3500 - val_loss: 3.4061 - val_accuracy: 0.2667
Epoch 4/50
4/4 [==============================] - 0s 20ms/step - loss: 2.9995 - accuracy: 0.3500 - val_loss: 3.2469 - val_accuracy: 0.2667
Epoch 5/50
4/4 [==============================] - 0s 22ms/step - loss: 2.8587 - accuracy: 0.3500 - val_loss: 3.0939 - val_accuracy: 0.2667
Epoch 6/50
4/4 [==============================] - 0s 22ms/step - loss: 2.7243 - accuracy: 0.3500 - val_loss: 2.9485 - val_accuracy: 0.2667
Epoch 7/50
4/4 [==============================] - 0s 22ms/step - loss: 2.6007 - accuracy: 0.3500 - val_loss: 2.8101 - val_accuracy: 0.2667
Epoch 8/50
4/4 [======================

In [18]:
model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 52ms/step - loss: 1.1137 - accuracy: 0.4333


[1.1137011051177979, 0.4333333373069763]

In [19]:
model.predict(x_test)

1/1 [==============================] - 0s 103ms/step


array([[0.11829055, 0.40789315, 0.4738163 ],
       [0.10237037, 0.40545484, 0.49217483],
       [0.16200817, 0.4168274 , 0.42116442],
       [0.21659361, 0.48629436, 0.29711205],
       [0.13588896, 0.3665184 , 0.4975926 ],
       [0.13208418, 0.4307364 , 0.43717936],
       [0.1831635 , 0.53543276, 0.28140375],
       [0.11470704, 0.40236294, 0.48293   ],
       [0.19506566, 0.51307523, 0.29185912],
       [0.17499182, 0.4328266 , 0.3921816 ],
       [0.14142226, 0.41012287, 0.44845495],
       [0.21224938, 0.4894889 , 0.29826173],
       [0.10702883, 0.3900272 , 0.502944  ],
       [0.19258197, 0.5211537 , 0.2862643 ],
       [0.19009715, 0.52505726, 0.28484562],
       [0.12985606, 0.39803097, 0.47211295],
       [0.14123906, 0.44010073, 0.41866022],
       [0.13977823, 0.4133798 , 0.446842  ],
       [0.10318892, 0.38970554, 0.5071055 ],
       [0.20187323, 0.5069935 , 0.29113328],
       [0.11863518, 0.4066402 , 0.47472462],
       [0.21975227, 0.47956875, 0.30067897],
       [0.

In [20]:
print(y_test)

[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 2 1 1 2 0 2 0 0 0 2 0 0 2 1 1]


In [21]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10,criterion="entropy",max_depth=4,random_state=0)
classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=10,
                       random_state=0)

In [22]:
y_pred = classifier.predict(x_test)

In [23]:
print(y_pred)

[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 1 1 1 2 0 2 0 0 0 2 0 0 2 1 1]


In [24]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[2 2]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [1 2]
 [1 1]
 [1 1]
 [2 2]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [0 0]
 [2 2]
 [0 0]
 [0 0]
 [2 2]
 [1 1]
 [1 1]]


In [25]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.9666666666666667

In [26]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[12  0  0]
 [ 0  8  0]
 [ 0  1  9]]
